### ISSUE TITLE
Check what Fable.Import.Browser split means for Elmish

### ISSUE THREAD

**Issue by et1975** [fable-elmish/elmish#100]
Fable 1.1 splits the Browser and Node imports out of the core, will probably need to import additional dependency. Maybe relocate the console logging into elmish-browser, while at it.

**Comment by alfonsogarciacaro** [comment]
I would like to make a PR before Thursday, but of course I'd be very happy if someone does it before ;) I was thinking to make elmish-browser dependent on Fable.Import.Browser. Not sure about logging, if it's only `printfn`s, it shouldn't need the Browser dependency.

**Comment by et1975** [comment]
I've tried `printf`, it works, but it takes over object formatting, whereas calling `console.log` lets the browser render the params as individual trees. I think this might be a good compromise - use `printf` in core elmish and use `console.log` in browser extensions.

**Comment by forki** [comment]
Would printf in user code still work?

Am 12.06.2017 19:07 schrieb "Eugene Tolmachev" <notifications@github.com>:

**Comment by alfonsogarciacaro** [comment]
`Console.WriteLine` with a single argument translates directly to `console.log` :+1:

**Comment by et1975** [comment]
@alfonsogarciacaro Kinda late, but maybe better than never question... I'm just replacing uses of `Fable.Import.Browser.console` with `System.Console` and wondering: isn't `console` sufficiently universal? Is there a JS runtime where that API wouldn't exist?

**Comment by alfonsogarciacaro** [comment]
Not sure, seems to work for the most used ones: browser, node (including Electron), react native... 😕

**Comment by et1975** [comment]
@alfonsogarciacaro Maybe we can keep it in Fable.Core then?

**Comment by alfonsogarciacaro** [comment]
Sure, maybe PR it to the Globals in Fable.Import.JS?

**Comment by et1975** [comment]
Will do 👍

**Comment by et1975** [comment]
Once the [PR](/fable-compiler/Fable/pull/1000) is merged and released will update elmish impl to use Import.JS globals.

**Comment by et1975** [comment]
Elmish 0.9.1 is using `console` from Fable.Core's `Import.JS`
