### ISSUE TITLE
best practices for webapi calls?

### ISSUE THREAD

**Issue by ctaggart** [fable-elmish/elmish#103]
I'm curious what the best practices are for making webapi calls with regards to Messages and sub components.

- Should all of the webapi calls be at the application level or should each component be able to make webapi calls?
- Should each webapi response be a separate message?

In a very simple app that is displaying a list of data, I have:

``` fsharp
    | Msg.Failure err ->
        console.error(err)
        model, Cmd.none
    | Msg.GetLatest ->
        let cmd = Cmd.ofPromise WebApi.getLatest () Msg.GotLatest (fun _ -> Msg.Failure "getLatest failed")
        model, cmd
    | Msg.GotLatest rows ->
        { model with LatestList = rows }, Cmd.none
```

Are there any good React apps that we can port to Fable to use as a more complicated example/sample? Something with a few react components and a few webapi calls would be perfect.

**Comment by et1975** [comment]
Excellent questions!

Following [certain Elm practices](http://blog.jenkster.com/2016/04/how-i-structure-elm-apps.html) I recommend having something like "Api.fs" for each submodule.

Once you implement a few API methods you realize:
1) REST + parametric polymorphism = match made in heaven
2) your API methods are just thin adapters between `fetch` API and your elmish module
3) Successes naturally map to a message in your submodule
4) Failures (as well as Warnings, and log-like messages in general) could benefit from a single Msg type shared throughout the app, as well as a central component to capture them all (and direct to some sort of ["Toaster"](http://react-toolbox.com/#/components/snackbar))

I don't know if there's anything out in the public to demonstrate this, but that's the approach we're using when building for our customers.

Heaving said that, I wouldn't be surprised if there are different/more sophisticated methods, I'd be curious to hear about it if someone wants to share.

**Comment by forki** [comment]
Can we apply it for the suave fable sample?

**Comment by et1975** [comment]
I think there's nothing actionable left for Elmish here.
