### ISSUE TITLE
ActivityIndicator has no time to spin in RN

### ISSUE THREAD

**Issue by forki** [fable-elmish/elmish#108]
let update msg model =
        match msg with
        | Start ->
            { model with 
                Status = InProgress }, Cmd.ofPromise longRunningPromise () Loaded Error
        | Loaded ->
            { model with 
                Status = Done }, Cmd.none
        // ...

    let view model dispatch =
        view [][
            // ...
            activityIndicator [ActivityIndicator.ActivityIndicatorProperties.Animating (model.Status = Status.InProgress)]
        ]

This doesn't work. The spinner will not start because the UI doesn't get rerendered.

**Comment by et1975** [comment]
Interesting, I'd think that in general animations wouldn't be handled by JS  thread, is there a working example in JS land?

**Comment by forki** [comment]
I dunno. did not do too much investigation yet. Just filed the issue because it was not working.

**Comment by et1975** [comment]
If you find more we can reopen.
