### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by vasily-kirichenko** [fable-elmish/elmish#111]
![image](https://user-images.githubusercontent.com/873919/30519481-5a7f3c6a-9ba0-11e7-8f66-b2fc320857c4.png)

![image](https://user-images.githubusercontent.com/873919/30519484-64e2b0ce-9ba0-11e7-88c1-6c96edc9790e.png)

**Comment by forki** [comment]
@alfonsogarciacaro I also noticed broken repl links. I think it was
something like repl.html or something before. We should consider a redirect


Am 17.09.2017 11:04 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by alfonsogarciacaro** [comment]
@forki Fable and Elmish websites are maintained separately. The new fable.io shouldn't have broken links but it seems Google results still point to old pages, I tried to use redirects but it's a bit tricky, see https://github.com/fable-compiler/fable-compiler.github.io/issues/8

**Comment by et1975** [comment]
Thanks, fixed the links.
