### ISSUE TITLE
How to periodically fetch a url and update the model with it?

### ISSUE THREAD

**Issue by vasily-kirichenko** [fable-elmish/elmish#112]
I'm trying this:

```fsharp
module Timer.State

let subscribe (initial: Model) : Cmd<Msg> =
    let sub (dispatch: Msg -> unit) : unit =
        window.setInterval ((fun _ ->
            try
                fetchAs<string> "http://google.com" [ RequestProperties.Mode RequestMode.Nocors ]
                |> Promise.map (fun weather ->
                    dispatch (GotWeather (DateTime.Now, weather)))
                |> Promise.start
            with e ->
                dispatch (FailedGotWeather (DateTime.Now, e.Message))
            ), 1000
        ) |> ignore
    
    Cmd.ofSub sub
```
and in `App.fs`
```fsharp
let subscription model =
  Cmd.map TimerMsg (Timer.State.subscribe model.timer)

// App
Program.mkProgram init update root
|> Program.withSubscription subscription
|> Program.toNavigable (parseHash pageParser) urlUpdate
|> Program.withReact "elmish-app"
```
It compiles, but F12 shows errors:

![image](https://user-images.githubusercontent.com/873919/30521041-48b9445a-9bc1-11e7-9f56-3e056ca2934d.png)

I'm sure I'm doing everything wrong :)

**Comment by alfonsogarciacaro** [comment]
Looks like a fetch error (maybe this? https://stackoverflow.com/questions/872206/http-status-code-0-what-does-this-mean-for-fetch-or-xmlhttprequest). You can also try `tryFetch` (pun not intended): https://github.com/fable-compiler/fable-powerpack/blob/9879adf889fbaa82e70c0cf0403dd8c45ff4a6e0/tests/FetchTests.fs#L59-L66

**Comment by vasily-kirichenko** [comment]
Yeah, thanks. It works for local url, but fails with code = 0 for external ones. Anyways, it's not an Elmish issue.

**Comment by ddunlea** [comment]
@vasily-kirichenko I'm currently hitting exactly the same issue; did you happen to find out what the underlying cause of the code = 0 was?

**Comment by vasily-kirichenko** [comment]
@ddunlea yes. It was CORS. It’s fixed as I turn CORS on on ElasticSearch (this is what I call).

**Comment by whitetigle** [comment]
Hi there, I'm currently struggling with the same CORS problem.

Case 1 : 
- CORS's been set on my host.
- I run fetch with no special mode
-> fails with 403 (I can see that in the browser network tab)

Case 2 : 
- CORS's been set on my host.
- I run fetch with **RequestMode.Nocors**
-> request succeeds with 200 status code in the browser network tab
**BUT**
fetch fails in the promise with a "0 for URL" error.

Would you have any idea why and how to solve this?
Thanks!

**Comment by whitetigle** [comment]
Ok. I was missing a **Access-Control-Allow-Origin** header on my server.

So working case is:
- Enable Cors on server
- Add *Access-Control-Allow-Origin* header on response
- use fetch **without** RequestMode.Nocors
