### ISSUE TITLE
Release Elmish 1.0.0

### ISSUE THREAD

**Issue by MangelMaxime** [fable-elmish/elmish#114]
### Description

@et1975 I think we can now release Elmish 1.0.0.

The last 2 things holding us was checking if Elmish works with netcore2.0 and waiting for Fable stable version.

cc @forki

**Comment by et1975** [comment]
Waiting on https://www.nuget.org/packages?q=Fable.PowerPack

**Comment by MangelMaxime** [comment]
Ah, yes I will make release it out of beta so :)

**Comment by MangelMaxime** [comment]
I just publish the new version: https://www.nuget.org/packages/Fable.PowerPack/1.3.0

**Comment by et1975** [comment]
Release 1.0 stable
