### ISSUE TITLE
Spelling in the readme about Redux

### ISSUE THREAD

**Issue by ShalokShalom** [fable-elmish/elmish#117]
Hi there - it can be my English, this is at least complicated to read for me: 

> For those familiar with Redux, the Fable applications targeting React or ReactNative may find Elmish a more natural fit..

**Comment by et1975** [comment]
I think it's grammatically correct - English is not my my 1st language either, but a PR has been made for this sentence already :) I'm open to another description as long as it conveys the same message.

**Comment by ShalokShalom** [comment]
I see no PR?

**Comment by et1975** [comment]
Oh, I meant there was one correction already. Any native speakers want to give it a go? cc @ScottShingler @2sComplement ?

**Comment by ScottShingler** [comment]
I'll take a stab at it.

**Comment by 2sComplement** [comment]
It is grammatically correct, though somewhat confusing. Does this convey the same message?
> Though Redux bindings do exist, Fable applications targeting React or ReactNative may find Elmish to produce cleaner and more idiomatic F# code.

**Comment by et1975** [comment]
The more we are discussing this the more I feel like it needs to be a table (Redux | Elmish) with side-by-side code comparison, cause "cleaner and more idiomatic" does not really convey the depth of despair one should feel looking at what Redux code looks like in F# :)

**Comment by ShalokShalom** [comment]
This sounds very awesome +1

**Comment by ShalokShalom** [comment]
Is there any table which shows a comparison between Elm and Elmish?

**Comment by et1975** [comment]
Not a table, but the [todo sample](/fable-elmish/sample-react-todomvc) is almost function-for-function port of [Elm sample](/evancz/elm-todomvc). Since both are in the ML family of languages and React is so close in terms of DSL, I'd say the gap between the two is almost non-existent.

**Comment by et1975** [comment]
I'll close this for now, we can reopen if anyone wants to add the comparison table...

**Comment by ShalokShalom** [comment]
You might want to put the TODO sample side by side to the Elm sample somewhere. 
So people can see the differences

**Comment by et1975** [comment]
@ShalokShalom Can you send a PR? Maybe also include [Fable-Redux verision](/fable-compiler/samples-browser/tree/master/src/redux-todomvc)...
