### ISSUE TITLE
Q: Canceling of open promise commands

### ISSUE THREAD

**Issue by forki** [fable-elmish/elmish#122]
I have a series of messages that come into my system. Whenever a message comes my update function triggers Cmd.ofPromise to load/show some data. This is an expensive operation and events are coming faster sometimes. Is there a way to cancel older promises from my elmish system?

/cc @Zaid-Ajaj @et1975 @alfonsogarciacaro @MangelMaxime

**Comment by et1975** [comment]
There's two things that you could do:
### Batching
Load into a buffer and process the whole batch on a threshold/timer, instead of processing individual messages.

### Splitting loading from rendering
You mention "show" so I'm assuming you have a non-react component that you feed the data to. You should be able to do what elmish already does: update the model on every incoming message, but show only when you get [a rendering opportunity](https://github.com/fable-elmish/react/blob/master/src/react.fs#L20).

**Comment by Zaid-Ajaj** [comment]
We can try integrate [Axios](https://github.com/axios/axios) with elmish instead of just Fable.PowerPack as Axios supports cancelling requests with CancelTokens

**Comment by forki** [comment]
No the problem is more that I need to throttle. Like that reactive
extensions combinator.

Am 30.10.2017 13:26 schrieb "Zaid Ajaj" <notifications@github.com>:

**Comment by Zaid-Ajaj** [comment]
If I understand correctly, you want either of two things:
 - Throttling: do not initiate a new request if an older request is still in progress or has intiated before some given timestamp.
 - Cancelling: when a new request comes in, cancel the one in-progress and keep the new request.

You can achieve the first one by keeping a timestamp of the time you initiated your last request and depending on that time, you can decide whether or not to initiate a new request. 

Maybe something like this:
```fs
type Model = {
// your stuff here
LastRequestStartTime : DateTime
LastRequestFinished: bool
}

Type Msg = 
  | StartLoadingData
  | ActuallyMakeRequest
  | RequestSuccess
  | RequestFailed
```

Your subscription should produce `StartLoadingData` and not `ActuallyMakeRequest`. Inside the `update` function you can decide whether or not to `ActuallyMakeRequest`:

```fs
let update msg state = 
   match msg with
   | StartLoadingData ->
      // if last request happned less than 30 seconds ago, then ignore
      if (DateTime.Now - state.LastRequestStartTime).Seconds < 30
      then state, Cmd.none
      elif not state.LastRequestFinished  
      then state, Cmd.none
      else { state with LastRequestStartTime = DateTime.Now;
                               LastRequestFinished = false }, Cmd.ofMsg ActuallyMakeRequest
   | ActuallyMakeRequest ->
      state, Cmd.ofPromise (yourPromiseHere)
   | RequestSuccess -> 
       // do stuff
       { state with  LastRequestFinished = true }, Cmd.none
   | RequestFailed ->
        // do stuff
       { state with  LastRequestFinished = true }, Cmd.none
```

Here I used both a boolean value and a timestamp to decide whether or not to start a new request, you can use either. Hope this helps

**Comment by et1975** [comment]
Closing: this is a task-level optimization, see #123 for the discussion about the role of `Cmd` in this.
