### ISSUE TITLE
**Discussion** Observable event streams

### ISSUE THREAD

**Issue by voronoipotato** [fable-elmish/elmish#128]
I just noticed that Cmd is not an event stream? I'm not seeing Observable anywhere in the code. I'm kind of curious why we're not using this. If we use observables then we could possibly leverage something like
[FSharp.Control.Reactive](http://fsprojects.github.io/FSharp.Control.Reactive/reference/fsharp-control-reactive-observablemodule.html ) You might have had very good reason for not doing this it just seems like reinventing the wheel to not use them?

**Comment by voronoipotato** [comment]
Admittedly this project may be much earlier on than I had originally thought. If that's the case what's the scope of adding this and what might be the possible reasons for not adding this in the future.

**Comment by voronoipotato** [comment]
I spoke with Reed Copsey and he helped me understand why this decision was made. It does however make me think that it still may be nice to have some helper methods for events that are time sensitive and therefore have a datetime attached to them. Like rx's debounce etc.

**Comment by voronoipotato** [comment]
You can close this issue, I understand better now.

**Comment by MangelMaxime** [comment]
If you need to debounce something you have a debouncer implementation [here](https://github.com/fable-compiler/fable-repl/blob/master/src/Monaco/Util.fs).

Also, you should be able to use it inside a subscription or create your own commands if that's needed.

**Comment by dbrattli** [comment]
Take a look at https://github.com/dbrattli/Reaction for using Observable event streams with Elmish.
