### ISSUE TITLE
JQuery integration problem

### ISSUE THREAD

**Issue by tigershark666** [fable-elmish/elmish#129]
### Description

I am testing the Javascript interop with JQuery and JQuery UI.
When loading the about page in the fable-elmish template modified as per the below code the div is not draggable.
If I replace the `.draggable()` with ` |> ignore` and save it and then add again `.draggable()` and save, it works as expected.
If at this point I reload the page it stops being draggable.
Even more strange, when adding `.draggable()` and saving it becomes immediately draggable upon save, if at that point I replace the `.draggable()` with ` |> ignore` and save it the div is still draggable.

I tested the same code in a standard fable app using the standard fable template and it works as expected without problems, so the problem seems specific to fable-elmish.
### Repro code

In the index.html add the following lines after the polyfill import:
```   
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script> 
```
in the Info/View.fs change the div properties to these: `[ ClassName "content"; Id "draggable"]` and add the following code at the bottom:
```
type IJQuery =
    abstract css : string * string -> IJQuery
    abstract draggable : unit -> unit

[<Emit("window['$']($0)")>]
let select (selector: string) : IJQuery = jsNative
[<Emit("window['$']($0)")>]
let ready (handler: unit -> unit) : unit = jsNative

ready(fun () -> select("#draggable").draggable())
```
In the Fable app the code is the same, the only difference is that I added the div directly in the index.html:
```
  <div id="draggable">
      <h1>Using HTML5 Canvas</h1>
  </div>
```

### Expected and actual results

The expected result is that the div should be always draggable when the `.draggable()` function is called and not draggable only when that function is not called regardless of the refresh / save sequence.
The actual result is that it is dependent from the sequence of refresh / save.

I have a feeling that it may be related to the loading lifecycle and when the JQuery.ready() function is actually called.

### Related information 

* fable-elmish version: 1.0.1
* fable-compiler version: 1.3.3
* fable-core version: 1.3.3
* Operating system: Mac OS X High Sierra 10.13.2
* Safari 11.0.2
* Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by et1975** [comment]
Sorry, no idea what might be happening. Try analyzing the DOM and step through the code to get some insights.
