### ISSUE TITLE
Add isNone to Cmd

### ISSUE THREAD

**Issue by robkuz** [fable-elmish/elmish#133]
When working with deeply nested `update` structures where parents call child `update` methods and rewrap the childrens returned sub cmds it would be nice to be able to have a generic means to shortcircuit when a child returns a `Cmd.none` so one does not end with a structure like 
`Cmd.map GrandparentMsg (Cmd.map ParentMsg Cmd.none)`

but one could do something like this

    if isNone subCmd then
       Cmd.none // this would return now a none of parent type
    else
       Cmd.map ParentMsg subCmd

anyone can write this in his own code but it would be nice to have it as part of the standard lib

    let isNone (x:List<_>) = List.length x = 0

**Comment by et1975** [comment]
You don't need to do this check, iterating over the list to map to correct type is no-op when the child returns Cmd.none. What am I missing?

**Comment by robkuz** [comment]
this is about rewrapping messages that bubble up to the top. I am not sure but I can not imagine that the main message loop does a deep inspection of all the nested commands and the messages and then decides to not dispatch that message because somewhere deep within it has a Cmd.none

**Comment by robkuz** [comment]
| RunExtension msg      ->
        let (submodel, subcmd) = updateExtension msg model.extension
        {model with extension = submodel}, Cmd.map RunExtension subcmd

just imagine that code above and assume that subcmd returns a `Cmd.none` what happens now?

**Comment by forki** [comment]
nothing will happen, because Cmd.none = [] so that map is noop

**Comment by robkuz** [comment]
got it
