### ISSUE TITLE
How make this work for native iOS/Android app (not forms)

### ISSUE THREAD

**Issue by mamcx** [fable-elmish/elmish#140]
I'm looking for an alternative to Xamarin.Forms for my multi-target app (iOS, Android & Web). I'm ok with write the UI for each target but wish to abstract the logic and "just" render the views.

I like how react work but don't wanna to do react native. And then I find elmish. This look like it could work. But I'm lost in what I need to do to make this work?

I understand that I need to provide the "setState" implementation, but not know how bridge the UI events and Elmish CMDs. 

I found https://github.com/dboris/elmish-forms but look like it copy all the code and then hack it. I wonder If is possible to do a cleaner work, and have a minimal setup..

P.D: BTW how is navigation handled?

**Comment by forki** [comment]
Here is a sample that uses F# with elmish on top of react-native:
https://github.com/SAFE-Stack/SAFE-Nightwatch
If you are interested in redux style on top of xamarin.forms then look at
@aspnetde's blog:
https://thomasbandt.com/fsharp-redux-store-for-xamarin-apps

Am 21.02.2018 07:22 schrieb "Pierre Irrmann" <notifications@github.com>:

**Comment by et1975** [comment]
There are some misperceptions about what ReactNative is, I wonder if you are thinking its running a browser under the hood? It kinda does, but not in a way of something like Electron or Cordova. Maybe if you could elaborate about your choice of runtime (Fable targets a JS runtime) we could offer some more guidance. Like @forki said, if JS runtime is of no interest, there are other options for unidirectional UIs (btw, there's beta of Elmish targeting netcore2.0 that you could use to run on Xamarin). Don Syme is working on Elmish.WPF renderer port for Xamarin as well. If JS runtime is preferable, then there might be some other options.

**Comment by mamcx** [comment]
I understand how react native work. I just don't want that huge dependency (and be forced to use JS or any X-To-JS language is not better), and yes, I have done the test to see how much it could buy me (similar with xamarin.forms) and I still think is better to do full native, IMHO. The only upside is easier theming/styling.

I have done before the task of build GUI builders in several languages (i work for erps/financial packages where is common to do this), but all ad-hoc. This time, I wish to implement a solid architecture instead of rely in my gut instinct :) ).

----

For the part of "make a DOM" I understand that, for example I could get a DSL like:

```
    let view (model:Model) =
        let ctrl 
            = [|
            UI.Text "Please Login"
            UI.Input "userName" "Input your userName" (getLastUserName)
            UI.InputSecure "pwd" "Input your pasword" ""
            |]

        UI.makeWindow "login" "Login" ctrl
```

I will need to build a diff for the controls. That is fine. Probably I will get into trouble when try to model something like tables/list with large amount of data.

Now the problem is how I connect the native controls events to model and vice versa.

**Comment by forki** [comment]
Serious question: do you want to build a mobil app or a mobile app
development framework. And what do you mean by going native? React native
is native.

Am 21.02.2018 15:05 schrieb "Mario Montoya" <notifications@github.com>:

**Comment by et1975** [comment]
So, no JS runtime, fine. Xamarin then, since we're talking F#, but no Forms. That eliminates Xamarin xplat story, as far as I know. So, binding to platform-specific controls, via Xamarin intermediary libs. You have a long way to go, but binding to events is the least of your problems, to get any reasonable  performance out of it, you need to implement a diffing algorithm, something similar to what React does. You'd define your DSL, using your example, something like: 
```fsharp
val text (attrs:TextAttributes list) : UIElement
val input (attrs:InputAttributes list) : UIElement
```
etc.
And then you'd diff on the produced elements and reconcile with what has been rendered already, constructing/destroying platform controls and hooking/unhooking the events and setting the properties.
It's no small endeavour and I look forward to seeing what you comeup with!

**Comment by mamcx** [comment]
> React native is native

Or more exactly, it use native UI. But it DEMAND the use of javascript as glue. And at the end the quality of controls is not uniform across platforms. 

----
> do you want to build a mobile app / development framework

Is a mix of both (plus web and command line utils). Is a common requirement for ERPs to provide a way to do customizations for each customer/company, so is better from the start to allow to dynamically build the UI as much as possible, but at the same time, is easy to restrict the complexity because is not necessary to provide pixel-perfect capabilities or full-feature form builders, ie, just a DSL is perfect.
