### ISSUE TITLE
Help for wrapping a function (task) into a command

### ISSUE THREAD

**Issue by MangelMaxime** [fable-elmish/elmish#141]
### Description

I have a function with this signature:

```fsharp
val toTask: 
   request : Http.Request<'Out> ->
   dispatch: Result<'Out,Http.Error> -> unit 
          -> unit
```

`dispatch` is a callback trigger when the `request` has been completed and so can be call at anytime.

I was able to wrap in using a custom command:

```fsharp
let toCmd (request : Http.Request<'Out>) : Cmd<Result<'Out, Http.Error>> =
    let bind dispatch =
        Http.toTask request dispatch
    [ bind ]
```

I was trying to use existing `Cmd` helpers, like `Cmd.performFunc`, `Cmd.ofSub`, etc. but failed to find a solution.

Is it possible to use existing `Cmd` helpers or should is my implementation the "right" way ?

**Comment by et1975** [comment]
@MangelMaxime did you figure it out?

**Comment by MangelMaxime** [comment]
@et1975 We can close for now, I am working on others project first.

I will re-open if needed.
