### ISSUE TITLE
Support plain Async<_> on Cmd

### ISSUE THREAD

**Issue by Nhowka** [fable-elmish/elmish#142]
Working on supporting multiple variables for Fable.Remoting, I made a function with [lots of arguments](https://github.com/Nhowka/Fable.Remoting/blob/CEBasedAPI/Fable.Remoting.Client/Proxy.fs#L83). That function is then reinterpreted with another signature, e.g. `f : int -> int -> Async<int>`.

When that function is called with partial application, the function turns into a `curriedFn` and expects all arguments, so calling `Cmd.ofAsync (f 1) 2 (Ok>>Msg) (Error>>Msg)` do nothing. A workaround is calling as  `Cmd.ofAsync (fun a -> f 1 a) 2 (Ok>>Msg) (Error>>Msg)`, but it would make the feature less friendly.

Calling an async workflow is not essentially referentially transparent, e.g. calling the following code prints different dates:
```fs
async {
    let time = async {printfn "%A" System.DateTime.Now}
    do! time
    do! Async.Sleep 1200
    do! time
} |> Async.RunSynchronously
```

As using an async workflow without arguments makes sense, I propose an addition, maybe named `Cmd.fromAsync` that is the same as `Cmd.ofAsync` but don't require an argument:
```fs
    let fromAsync (task: Async<_>)
                (ofSuccess: _ -> 'msg)
                (ofError: _ -> 'msg) : Cmd<'msg> =
        let bind dispatch =
            async {
                let! r = task |> Async.Catch
                dispatch (match r with
                         | Choice1Of2 x -> ofSuccess x
                         | Choice2Of2 x -> ofError x)
            }
        [bind >> Async.StartImmediate]
```

**Comment by et1975** [comment]
I tried to keep `async` similar to `promise` and plain func in feel, but yes - the `async` is "cold" and re-evaluated every time while the other two are "hot" and once arguments are bound will collapse to a value. However, could you elaborate on
> the function turns into a curriedFn and expects all arguments, so calling `Cmd.ofAsync (f 1) 2 (Ok>>Msg) (Error>>Msg)` do nothing.

What do you expect `f 1 2` to do that `(f 1) 2` does not do?

**Comment by Nhowka** [comment]
When I call `f 1 2`, it gets directly into the function body. So inside I get the args `(1, 2, undefined, undefined,...)`. When called by `(f 1) 2`, I get a intermediate function that only gets into the body if the target function also has 13 arguments.

**Comment by Nhowka** [comment]
Here is a repro on [Fable Repl](http://fable.io/repl/#?code=open%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0Aopen%20Fable.Import.Browser%0A%0Alet%20toQuery%20qs%20%3D%0A%20%20%20%20fun%20a%20b%20c%20d%20-%3E%0A%20%20%20%20%20%20%20%20let%20args%20%3D%20%5Bbox%20a%3Bbox%20b%3Bbox%20c%3Bbox%20d%5D%20%7C%3E%20List.takeWhile%20((%3C%3E)null)%0A%20%20%20%20%20%20%20%20let%20row%20%3D%20document.querySelector(qs)%20%3A%3F%3E%20HTMLTableRowElement%0A%20%20%20%20%20%20%20%20args%0A%20%20%20%20%20%20%20%20%7C%3E%20List.iter%0A%20%20%20%20%20%20%20%20%20%20%20%20(fun%20e%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20let%20element%20%3D%20document.createElement_td()%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20element.textContent%20%3C-%20(string%20e)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20row.appendChild%20element%20%7C%3E%20ignore%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%0Atype%20Test%20%3D%20%7B%0A%20%20%20%20FunA%3A%20int%20-%3E%20int%20-%3E%20unit%0A%20%20%20%20FunB%3A%20int%20-%3E%20int%20-%3E%20int%20-%3E%20int%20-%3E%20unit%0A%7D%0A%0A%5B%3CEmit(%22%242%5B%240%5D%20%3D%20%241%22)%3E%5D%0Alet%20setProp%20(propName%3A%20string)%20(propValue%3A%20obj)%20(any%3A%20obj)%20%3A%20unit%20%3D%20jsNative%0A%0Alet%20proxy%20%3D%20obj%20()%0AsetProp%20%22FunA%22%20(toQuery%20%22.FunA%22)%20proxy%0AsetProp%20%22FunB%22%20(toQuery%20%22.FunB%22)%20proxy%0Alet%20instance%20%3D%20unbox%3CTest%3E%20proxy%0Ainstance.FunA%201%202%0Alet%20curriedA%20%3D%20(instance.FunA%201)%0AcurriedA%202%0Ainstance.FunB%201%202%203%204%0Alet%20curriedB%20%3D%20(instance.FunB%201%202)%0AcurriedB%203%204%0A&html=%3Chtml%3E%0A%0A%3Chead%3E%0A%20%20%20%20%3Cmeta%20http-equiv%3D%22Content-Type%22%20content%3D%22text%2Fhtml%3Bcharset%3Dutf-8%22%3E%0A%3C%2Fhead%3E%0A%0A%3Cbody%3E%0A%20%20%20%20%3Ctable%20class%3D%22table%22%20width%3D%22400%22%20height%3D%22400%22%3E%0A%20%20%20%20%20%20%20%20%3Ctr%20class%3D%22FunA%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EFunA%3C%2Ftd%3E%0A%20%20%20%20%20%20%20%20%3C%2Ftr%3E%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Ctr%20class%3D%22FunB%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EFunB%3C%2Ftd%3E%0A%20%20%20%20%20%20%20%20%3C%2Ftr%3E%20%20%20%20%20%20%20%20%0A%20%20%20%20%3C%2Ftable%3E%0A%3C%2Fbody%3E%0A%0A%3C%2Fhtml%3E%0A). As you can see, `FunA` gets called only once, but when partially applied, nothing happens. As `FunB` has all 4 arguments, it gets called twice.

**Comment by et1975** [comment]
There's probably some nuance I don't understand, but at the point of `Async.Catch` all the arguments are bound regardless of how they were passed in. Are you saying it makes difference wether all the arguments are bound before the async block starts? Are you intending to hold on to your `async` task and pass it over and over again?

**Comment by Nhowka** [comment]
Here is an even better example on [Repl](http://fable.io/repl/#?code=open%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0Aopen%20Fable.Import.Browser%0A%0Alet%20table%20%3D%20document.querySelector(%22.table%22)%20%3A%3F%3E%20HTMLTableElement%0A%0Alet%20fn%20%3D%0A%20%20%20%20fun%20title%20a%20b%20c%20-%3E%0A%20%20%20%20%20%20%20%20let%20args%20%3D%20%5Bbox%20a%3Bbox%20b%3Bbox%20c%5D%20%7C%3E%20List.takeWhile%20((%3C%3E)null)%0A%20%20%20%20%20%20%20%20let%20row%20%3D%20document.createElement_tr()%0A%20%20%20%20%20%20%20%20let%20t%20%3D%20document.createElement_th()%0A%20%20%20%20%20%20%20%20t.textContent%20%3C-%20title%0A%20%20%20%20%20%20%20%20row.appendChild%20t%20%7C%3E%20ignore%0A%20%20%20%20%20%20%20%20args%0A%20%20%20%20%20%20%20%20%7C%3E%20List.iter%0A%20%20%20%20%20%20%20%20%20%20%20%20(fun%20e%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20let%20element%20%3D%20document.createElement_td()%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20element.textContent%20%3C-%20(string%20e)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20row.appendChild%20element%20%7C%3E%20ignore%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%0A%20%20%20%20%20%20%20%20table.appendChild%20row%0Atype%20Test%20%3D%20%7B%0A%20%20%20%20FunA%3A%20string%20-%3E%20int%20-%3E%20unit%0A%20%20%20%20FunB%3A%20string%20-%3E%20int%20-%3E%20int%20-%3E%20int%20-%3E%20unit%0A%7D%0A%0A%5B%3CEmit(%22%242%5B%240%5D%20%3D%20%241%22)%3E%5D%0Alet%20setProp%20(propName%3A%20string)%20(propValue%3A%20obj)%20(any%3A%20obj)%20%3A%20unit%20%3D%20jsNative%0A%0Alet%20proxy%20%3D%20obj%20()%0AsetProp%20%22FunA%22%20fn%20proxy%0AsetProp%20%22FunB%22%20fn%20proxy%0Alet%20instance%20%3D%20unbox%3CTest%3E%20proxy%0Ainstance.FunA%20%22FunA%20Total%3A%22%201%0Alet%20curriedA%20%3D%20(instance.FunA%20%22FunA%20Curried%3A%22)%0AcurriedA%201%0Ainstance.FunB%20%22FunB%20Total%3A%22%201%202%203%0Alet%20curriedB%20%3D%20(instance.FunB%20%22FunB%20Curried%3A%22%201)%0AcurriedB%202%203&html=%3Chtml%3E%0A%0A%3Chead%3E%0A%20%20%20%20%3Cmeta%20http-equiv%3D%22Content-Type%22%20content%3D%22text%2Fhtml%3Bcharset%3Dutf-8%22%3E%0A%3C%2Fhead%3E%0A%0A%3Cbody%3E%0A%20%20%20%20%3Ctable%20class%3D%22table%22%20width%3D%22400%22%20height%3D%22400%22%3E%3C%2Ftable%3E%0A%3C%2Fbody%3E%0A%0A%3C%2Fhtml%3E%0A). If it's not called with 4 arguments the curried version will not be called.

**Comment by et1975** [comment]
Thank you for the examples, however as I suspected, this is seriously convoluted. You are circumventing the type system, which is fine by itself, but it's a really poor reason to request addition to the Elmish core.

**Comment by Nhowka** [comment]
It's for the next version of Fable.Remoting. But it's ok, I'll try to find another way.
