### ISSUE TITLE
Type provider to import HTML views

### ISSUE THREAD

**Issue by xperiandri** [fable-elmish/elmish#143]
Wouldn't it be useful to have HTML type provider to import HTML views?
https://twitter.com/MangelMaxime/status/976224754486140928?s=09
Like this converter but with compile time conversion or injection (depending on how it works now).

Basically DOM construction in F# required only for conditional construction of come DOM tree branch, don't it?

**Comment by MangelMaxime** [comment]
Fable does not support TypeProvider yet so it's not possible.

Also, I am not sure of the benefit of adding/maintaining a TypeProvider for this case (would need a custom HTML parser, my converter is using a JavaScript lib).
How would you hook event into this kind of view. 

I believe, users should have strong typed code into their application and not html strings. I will provide a VSCode extension to ease the converter usage. IMO it's enough to have a good user experience and low maintaince cost.

**Comment by xperiandri** [comment]
About experience I don't have any doubts but maintainability is a question.

**Comment by MangelMaxime** [comment]
What's the benefit of writing a string instead of a typed DSL ? Just for that IMO the user experience is bad.

**Comment by et1975** [comment]
I'm with @MangelMaxime  on this, I don't think JSX/XML/HTML is particularly nice model to work with, especially if you consider bindings and event handlers (which would need to be compiler verified).
Having said that, you of course are free to develop it, I imagine it would be targeting React so we can continue the conversation in the [react](/fable-elmish/react) repo.
