### ISSUE TITLE
UWP/Windows ReactNative samples

### ISSUE THREAD

**Issue by et1975** [fable-elmish/elmish#28]
Would be nice to have RN samples targeting Windows/UWP, seems like right now that would be the only way to program UWP apps in F#. 
I don't have a Windows to try it on, so hopefully someone can PR this.

**Comment by davidpodhola** [comment]
Only [Navigation sample](https://github.com/fable-compiler/fable-elmish/tree/master/samples/react-native/navigation) was changed to support [react-native-windows](https://github.com/ReactWindows/react-native-windows). Need to go through the other `samples\react-native` too.

**Comment by et1975** [comment]
Closing for now
