### ISSUE TITLE
Create templates for fable-elmish-react and fable-elmish-react-native projects

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-elmish/elmish#50]
@et1975 @MangelMaxime Could you please create templates for fable-elmish-react and fable-elmish-snabbdom projects? You can take the [simple Fable template](https://github.com/fable-compiler/Fable/tree/narumi/src/templates/simple) as reference. Or if you prefer, you can just add the files and I'll take care of the .nuspec and template.json configuration 👍 

> The [documentation for dotnet SDK templates](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates) is still incomplete but there's [a tutorial here](http://pioneercode.com/post/how-to-create-a-dot-net-new-project-template-in-dot-net-core) if you need help.

**Comment by alfonsogarciacaro** [comment]
Now that https://github.com/fable-compiler/Fable/issues/781 it'd be nice to have a template ready for F# eXchange, so basically I'd need it... NOW! sorry ;)

A more or less full-app with navigation and debugger will be nice. You can just do the code and I'll take care of the template config and Nuget publishing. The only thing you need to remember is you can use a string like `FableElmishReactTemplate` (no periods or hyphens allowed, I think) that will be replaced **both in file name and content** with the project name given by the user.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Nice news :)

I was waiting for it to work again with Elmish. I should have the time to create the template today or tomorrow.

**Comment by et1975** [comment]
Blocked, waiting for https://github.com/fable-compiler/Fable/issues/804

**Comment by et1975** [comment]
Closing, will be tracked in [templates](fable-elmish/templates) repo if needed
