### ISSUE TITLE
Generate docs

### ISSUE THREAD

**Issue by et1975** [fable-elmish/elmish#6]
Should match fable process and style.
Should have running React examples on github.io.

**Comment by alfonsogarciacaro** [comment]
> Should match fable process and style.

I want to update the Fable web build process to make the samples build faster and also make it easier for others to edit it (add samples, links to blog posts, etc). So please don't use the current Fable website as strict model.

I love what @MangelMaxime did with the fable-arch website and I would like to rewrite the web using that approach (using elmish).

**Comment by MangelMaxime** [comment]
For the new docs site of Elmish, I think the sample will be hosted via "github pages".

We will probably need some sort of convention, to add a `README.md` or `DOC.md` file which add documentation/explanation to the sample.

Those files are need only if the sample is a "tutorial" if not we will simply display it directly :)

I am currently porting the old doc site to the same architecture used on Elmish template.
