### ISSUE TITLE
Pretty printing of messages in chrome debugger

### ISSUE THREAD

**Issue by forki** [fable-elmish/elmish#73]
IIRC we had nice messages in the chrome debugger. Now we see only "tag" 0,1,2

![image](https://cloud.githubusercontent.com/assets/57396/25003103/14ba5ea8-204e-11e7-8664-487beef0fc82.png)

@alfonsogarciacaro Is that a regression with narumi? Can we have nice things back?

**Comment by Pauan** [comment]
Probably related to https://github.com/fable-compiler/Fable/issues/810, which has been fixed.

**Comment by forki** [comment]
so it's @alfonsogarciacaro slacking?

**Comment by et1975** [comment]
no, it's me not keeping up with narumi.

**Comment by forki** [comment]
slacker! ;-)

**Comment by et1975** [comment]
released with fable-elmsih@0.9.0-beta-7

**Comment by forki** [comment]
thanks!!!!

**Comment by MangelMaxime** [comment]
@et1975 @forki 
Can we close this issue ?

**Comment by forki** [comment]
Yes please close. I will reopen if something is still wrong. Thx

Am 14.04.2017 9:06 vorm. schrieb "Maxime Mangel" <notifications@github.com>:

**Comment by forki** [comment]
Just tried with latest master. still shows tags as 0

![image](https://cloud.githubusercontent.com/assets/57396/25064827/3455a3ce-2203-11e7-8a31-ae48009a5a49.png)

so at least something yarny needs to happen?!

**Comment by alfonsogarciacaro** [comment]
@forki I had tested with latest fable-elmish-react template and it was working (I added `|> Program.withConsoleTrace` manually). Please note the change was made in the fable-elmish-debugger package not in fable-elmish.

**Comment by forki** [comment]
I was trying on the counter sample here. Not working.

**Comment by alfonsogarciacaro** [comment]
@forki Have you checked that you're using the latest fable-elmish-debugger package (0.9.0-beta-6), the `debugger.fs` file should look like [this](https://github.com/fable-elmish/debugger/blob/5c77f18a7fbc6b17a203c7ab6d8a631582bee869/src/debugger.fs#L45).

**Comment by et1975** [comment]
@forki I just tested it on newly relocated [repo](https://github.com/fable-elmish/sample-react-counter) and it looks alright to me, can you try and reproduce it there?

**Comment by forki** [comment]
Yes works on the new repo
