### ISSUE TITLE
[Discussion] move to the fable-elmish org

### ISSUE THREAD

**Issue by et1975** [fable-elmish/elmish#86]
Just a thread for people discuss the transition.

### Why are we doing this?
From the begging I wasn't comfortable with mono-repo approach the rest of fable (and JS) ecosystem seems to be following. Specifically:
- As the project grows, there are some things I care more about and would like to have a complete control over w/o involving a committee in a discussion. I promise to restrict the dictatorship to the absolute minimum of code, that's why I favour a lot of small libs and a project-per-lib approach.
- As a member of the org you'll have the ability to add your own projects and organize it any way you like, I will not police what goes in your projects, although I will offer an advise if you ask for it.
- I'd like to tie a build to the release, and use all the facilities of CI and github that go with it.

Elm-org follows this structure and from the discussion with @MangelMaxime he felt the same way, so there you have it.

### How will we tie all the projects together?
We'll create the github.io org site and collect the gh-pages from all the subprojects.
Your docs, your samples, etc will be listed once you PR the links/changes to the main site.

### How will I be able to update a bunch of project at once?
Hopefully the need for this will be minimal, but you can create a root org folder and checkout multiple projects under it, thus having the same search-replace capabilities as you do now.

**Comment by forki** [comment]
Can you please give full access to the core team so that we can push to sample repos?
