### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-elmish/elmish#87]
That autogenerated logo in the Github org page looks a bit sad ;)

**Comment by Zaid-Ajaj** [comment]
☝️

**Comment by et1975** [comment]
How is this?

**Comment by alfonsogarciacaro** [comment]
Looks cool! :clap:

**Comment by forki** [comment]
Huh? Where is the logo? Can't see anything

**Comment by alfonsogarciacaro** [comment]
In [fable-elmish org page](https://github.com/fable-elmish)

**Comment by MangelMaxime** [comment]
Looks cool for me too :)

**Comment by et1975** [comment]
![elmish](https://cloud.githubusercontent.com/assets/623703/25090276/45551ae4-2350-11e7-88f0-497128959e99.png)

In case anyone wants to use it...

**Comment by forki** [comment]
MIT licensed? 

Good work btw

**Comment by et1975** [comment]
Everything in elmish is Apache 2 licensed.

**Comment by forki** [comment]
Thx. Can we still dual license everything with MIT. We had some issues with
fake (don't ask me I'm no. Lawer). But dual license made it go away

Am 17.04.2017 15:40 schrieb "Eugene Tolmachev" <notifications@github.com>:

**Comment by et1975** [comment]
I'm not a lawyer either, but there are good reasons to choose Apache over MIT.  If there's an actual problem we can discuss it.

**Comment by forki** [comment]
No I meant to use both as dual license. This makes it usable for even more
people

Am 17.04.2017 15:54 schrieb "Eugene Tolmachev" <notifications@github.com>:
