### ISSUE TITLE
Whats the standard renderer to use for starting out?

### ISSUE THREAD

**Issue by Kurren123** [fable-elmish/elmish#90]
Seeing as [fable arch was merged into elmish](https://github.com/fable-elmish/elmish/issues/38) I'm guessing virtual DOM isn't recommended any more (and [this example](http://fable.io/samples/virtualdom/index.html) doesn't work). Also it looks like [elmish Snabbdom is depreciated](https://github.com/fable-elmish/elmish/issues/62). Does this mean that the only recommended renderer left is Elmish react?

**Comment by Zaid-Ajaj** [comment]
@Kurren123 Yes, for single page apps you would use React. There is work in progress on making React Native work for mobile apps.

**Comment by MangelMaxime** [comment]
As @Zaid-Ajaj said, we now support only React as a renderer for the "DOM browser".
