### ISSUE TITLE
Is it possible to use third party react components?

### ISSUE THREAD

**Issue by Kurren123** [fable-elmish/elmish#92]
Let's say I wanted to use [chartify](https://kiqs.github.io/chartify/example/). How easy is this with fable-elmish?

**Comment by et1975** [comment]
Short answer: Yes, it looks like chartify would play nice with elmish. 

Long answer:
Elmish is not concerned so much with UI technology, but with the state. The lib in question is designed for React, so with react-elmish you can render it. More importantly, it appears to take the state as a property, which makes it possible for elmish to manage the state for it.

You will want to create bindings for the lib, here's an [example of bindings](https://github.com/Prolucid/fable-react-grid-system) for another React lib. And afterwards, you just use it like any React class in your UI.

**Comment by alfonsogarciacaro** [comment]
Just in case, here's also an example of how to [render React components dynamically](https://github.com/fable-compiler/fable-electron/blob/30ba96bb18ba68c9b9f3b6505a36c7faa30859ec/samples/material-ui/src/Renderer/Renderer.fs) (without bindings).

**Comment by joahim** [comment]
See https://github.com/fable-compiler/fable-react/blob/master/docs/using-third-party-react-components.md for a detailed description of how to use the third party react components with Elmish.
